In [1]:
import import_ipynb
import numpy as np
import matplotlib.pyplot as plt
import os
from pathlib import Path

# cur_path = os.getcwd()
# os.chdir('../')
from Judd_Ofeld_Base import Judd_Ofelt, Spectra, Data_U
# os.chdir(cur_path)

_____________
## Сведенья об объекте
* Масса стекла ~50 грамм
* молярная доля как Nd2O3 в стекле 0.5 моль%
* Плотности стекол с Nd - 3,14;
* Показатель преломления на длинне волны 589  - 1.55
* N_A = 6.022*1e23
* Молярная масса ZnO - 81.389
* Молярная масса P2O5 - 141.943
* Молярная масса Nd2O3 - 336.477
* Моль% 57.00 ZnO 42.50 P2O5 0.5 Nd2O3

**Относительная молярная масса стекла с Nd2O3 (0.57*81.389 + 0.425*141.943 + 0.005 * 336.477)**
_____________

In [2]:
## Определение концентрации Er (ions/cm3)
Md_Nd = 336.477*0.005/((0.57)*81.389 + 0.425*141.943 + 0.005 * 336.477)
print(f'Массовая доля Nd2O3  {Md_Nd}')
Ny_Nd = 50*Md_Nd/336.477*2
print(f'Кол-во вещества Nd в стекле Nd2O3 {Ny_Nd}')
N_A = 6.02214076e23
c_ND = Ny_Nd * N_A *3.14 / 50
print(f'Nd concantration = {c_ND} (ions/cm3)')

Массовая доля Nd2O3  0.015520172575820881
Кол-во вещества Nd в стекле Nd2O3 0.004612550806093992
Nd concantration = 1.7444226176244276e+20 (ions/cm3)

_____________________
## Calculations
_____________________

In [3]:
path_to_U_Nd = Path('./U_data/Nd_Carnal_Ground.txt')
path_to_Pristine_PZ_Nd = Path('./Experiment/Abs_Pristine_PZ_Nd.txt')

In [4]:
CORR = 2.3/0.1440     # Для перевода спектра к обратным сантиметрам
REF_IND = 1.55        # показатель преломления

In [5]:
data_U_Nd = Data_U(path_to_U_data=path_to_U_Nd )

In [6]:
data_U_Nd.data_U.head()

,Unnamed: 0,TERM_i,TERM_f,Term,Energy,U2,U4,U6,Lambda,J_i,J_f,S_f,L_f
0,0,2P3/2,4I9/2,2P3/2-4I9/2,26189.0,0.0000,0.0010,0.0005,381.839704,1.5,4.5,1.5,6.0
1,1,2D5/2,4I9/2,2D5/2-4I9/2,23769.0,0.0000,0.0002,0.0017,420.716059,2.5,4.5,1.5,6.0
2,2,2P1/2,4I9/2,2P1/2-4I9/2,23223.0,0.0000,0.0396,0.0000,430.607587,0.5,4.5,1.5,6.0
3,3,2D3/2,4I9/2,2D3/2-4I9/2,21190.0,0.0000,0.0202,0.0001,471.920717,1.5,4.5,1.5,6.0
4,4,4G7/2,4I9/2,4G7/2-4I9/2,19058.0,0.0596,0.1709,0.0566,524.714031,3.5,4.5,1.5,6.0

In [7]:
spectra_Pristine_PZ_Nd = Spectra(path_to_spectra = path_to_Pristine_PZ_Nd, delimiter='\t',skiprows=1)

In [8]:
spectra_Pristine_PZ_Nd.y = spectra_Pristine_PZ_Nd.y*CORR

# Обрезание и повторная отрисовка спектра поглощения при необходимости
# crop_se = [500,750]  # Границы для обрезания спектра
# spectra_Pristine_PZ_Nd.crop_spectra(x_start=crop_se[0], x_end=crop_se[1])
# spectra_Pristine_PZ_Nd.plot_spectra()

### Отсеиваем полосы поглащения необходимые для рассмотрения

In [9]:
MAX_FROM_U_Nd = data_U_Nd.data_U.Lambda.values

In [10]:
m_val_prits_Nd = spectra_Pristine_PZ_Nd.set_maxima(tolerance=1,max_from_U=MAX_FROM_U_Nd)

In [11]:
jo_prist_Nd = Judd_Ofelt(U_data=data_U_Nd, spectra=spectra_Pristine_PZ_Nd)

In [12]:
jo_prist_Nd.define_shift(tol=20.)

Optimization terminated successfully.
         Current function value: 11.303241
         Iterations: 1
         Function evaluations: 14
         Gradient evaluations: 7

np.float64(-0.1616181912729774)

In [13]:
jo_prist_Nd.get_correct_maxima_df(del_tol=10, merge_tol=10)

,Unnamed: 0,TERM_i,TERM_f,Term,Energy,U2,U4,U6,Lambda,J_i,J_f,S_f,L_f,Preliminary_spectra_max,Group,Grouped
1,1,2D5/2,4I9/2,2D5/2-4I9/2,23769.0,0.0000,0.0002,0.0017,420.716059,2.5,4.5,1.5,6.0,429.0,0,True
2,2,2P1/2,4I9/2,2P1/2-4I9/2,23223.0,0.0000,0.0396,0.0000,430.607587,0.5,4.5,1.5,6.0,429.0,0,True
3,3,2D3/2,4I9/2,2D3/2-4I9/2,21190.0,0.0000,0.0202,0.0001,471.920717,1.5,4.5,1.5,6.0,472.0,1,False
4,4,4G7/2,4I9/2,4G7/2-4I9/2,19058.0,0.0596,0.1709,0.0566,524.714031,3.5,4.5,1.5,6.0,524.0,2,False
5,5,4G7/2,4I9/2,4G7/2-4I9/2,17234.0,0.0707,0.1720,0.0274,580.248346,3.5,4.5,1.5,6.0,580.0,3,True
6,6,4G5/2,4I9/2,4G5/2-4I9/2,17193.0,0.8975,0.4126,0.0346,581.632060,2.5,4.5,1.5,6.0,582.0,3,True
7,7,4S3/2,4I9/2,4S3/2-4I9/2,13456.0,0.0000,0.0025,0.2347,743.162901,1.5,4.5,1.5,6.0,743.0,4,True
8,8,4F7/2,4I9/2,4F7/2-4I9/2,13384.0,0.0011,0.0406,0.4272,747.160789,3.5,4.5,1.5,6.0,747.0,4,True

### Проводим подгонку площадей под полосами поглащения с помощью функций Гаусса.

In [14]:
_ = jo_prist_Nd.init_boundaries()

In [15]:
jo_prist_Nd.set_boundaries_and_fit()

,Unnamed: 0,TERM_i,TERM_f,Term,Energy,U2,U4,U6,Lambda,J_i,...,Group,Grouped,Boundaries_start_idx,Boundaries_end_idx,Num_Gauss,Paired,Gauss_parameters,Bkg_parameters,Lambda_mean,Gauss_AUC
0,2,2P1/2,4I9/2,2P1/2-4I9/2,23223.0,0.0000,0.0396,0.0000,430.607587,0.5,...,0,False,22.0,50.0,3.0,False,"[[0.1024681673, 429.0542728957, 0.7518521063],...","(0.9169371886992258, 0.9008434837300567)",430.715711,0.905253
1,3,2D3/2,4I9/2,2D3/2-4I9/2,21190.0,0.0000,0.0202,0.0001,471.920717,1.5,...,1,False,43.0,88.0,5.0,False,"[[0.0820270056, 461.2128484103, 3.4064912078],...","(0.9075022686531856, 0.8545756635578837)",469.786252,3.782262
2,4,4G7/2,4I9/2,4G7/2-4I9/2,19058.0,0.0596,0.1709,0.0566,524.714031,3.5,...,2,False,87.0,153.0,5.0,True,"[[0.6467753975, 524.3829516513, 3.0680884216],...","(0.8602358053986678, 0.8357810753465884)",526.391576,12.022245
3,5,4G7/2,4I9/2,4G7/2-4I9/2,17234.0,0.0707,0.1720,0.0274,580.248346,3.5,...,3,True,150.0,213.0,3.0,False,"[[2.3966986627, 572.4868144353, 3.0010358773],...","(0.8322025226732457, 0.7441538841378393)",580.086728,82.633184
4,6,4G5/2,4I9/2,4G5/2-4I9/2,17193.0,0.8975,0.4126,0.0346,581.632060,2.5,...,3,True,150.0,213.0,3.0,False,"[[2.9855617625, 581.6813038966, 4.3041608063],...","(0.8322070631063317, 0.7441577550009111)",581.470441,82.633421
5,7,4S3/2,4I9/2,4S3/2-4I9/2,13456.0,0.0000,0.0025,0.2347,743.162901,1.5,...,4,True,318.0,376.0,5.0,False,"[[1.3211423737, 735.5254123055, 2.9781305007],...","(0.6938051892418188, 0.6730769645085061)",743.001283,40.549559
6,8,4F7/2,4I9/2,4F7/2-4I9/2,13384.0,0.0011,0.0406,0.4272,747.160789,3.5,...,4,True,309.0,373.0,5.0,False,"[[0.9458383036, 735.1023791217, 2.36932294], [...","(0.6543955519529999, 0.6681193969638923)",746.999171,41.757051

### Расчет сил осцилляторов

In [16]:
jo_prist_Nd.set_constant_refractive_index(n=REF_IND)

,Unnamed: 0,TERM_i,TERM_f,Term,Energy,U2,U4,U6,Lambda,J_i,...,Grouped,Boundaries_start_idx,Boundaries_end_idx,Num_Gauss,Paired,Gauss_parameters,Bkg_parameters,Lambda_mean,Gauss_AUC,n
0,2,2P1/2,4I9/2,2P1/2-4I9/2,23223.0,0.0000,0.0396,0.0000,430.607587,0.5,...,False,22.0,50.0,3.0,False,"[[0.1024681673, 429.0542728957, 0.7518521063],...","(0.9169371886992258, 0.9008434837300567)",430.715711,0.905253,1.55
1,3,2D3/2,4I9/2,2D3/2-4I9/2,21190.0,0.0000,0.0202,0.0001,471.920717,1.5,...,False,43.0,88.0,5.0,False,"[[0.0820270056, 461.2128484103, 3.4064912078],...","(0.9075022686531856, 0.8545756635578837)",469.786252,3.782262,1.55
2,4,4G7/2,4I9/2,4G7/2-4I9/2,19058.0,0.0596,0.1709,0.0566,524.714031,3.5,...,False,87.0,153.0,5.0,True,"[[0.6467753975, 524.3829516513, 3.0680884216],...","(0.8602358053986678, 0.8357810753465884)",526.391576,12.022245,1.55
3,5,4G7/2,4I9/2,4G7/2-4I9/2,17234.0,0.0707,0.1720,0.0274,580.248346,3.5,...,True,150.0,213.0,3.0,False,"[[2.3966986627, 572.4868144353, 3.0010358773],...","(0.8322025226732457, 0.7441538841378393)",580.086728,82.633184,1.55
4,6,4G5/2,4I9/2,4G5/2-4I9/2,17193.0,0.8975,0.4126,0.0346,581.632060,2.5,...,True,150.0,213.0,3.0,False,"[[2.9855617625, 581.6813038966, 4.3041608063],...","(0.8322070631063317, 0.7441577550009111)",581.470441,82.633421,1.55
5,7,4S3/2,4I9/2,4S3/2-4I9/2,13456.0,0.0000,0.0025,0.2347,743.162901,1.5,...,True,318.0,376.0,5.0,False,"[[1.3211423737, 735.5254123055, 2.9781305007],...","(0.6938051892418188, 0.6730769645085061)",743.001283,40.549559,1.55
6,8,4F7/2,4I9/2,4F7/2-4I9/2,13384.0,0.0011,0.0406,0.4272,747.160789,3.5,...,True,309.0,373.0,5.0,False,"[[0.9458383036, 735.1023791217, 2.36932294], [...","(0.6543955519529999, 0.6681193969638923)",746.999171,41.757051,1.55

In [17]:
jo_prist_Nd.set_concentration(conc=c_ND/1e20)

In [18]:
jo_prist_Nd.concentration

1.7444226176244275

In [19]:
jo_prist_Nd.result_df.n = jo_prist_Nd.result_df.n.round(decimals=3)
jo_prist_Nd.result_df.Lambda_mean = jo_prist_Nd.result_df.Lambda_mean.round(decimals=3)
jo_prist_Nd.result_df.Gauss_AUC = jo_prist_Nd.result_df.Gauss_AUC.round(decimals=4)
jo_prist_Nd.result_df[['U2','U4','U6']] = jo_prist_Nd.result_df[['U2','U4','U6']].round(decimals=4)

In [20]:
jo_prist_Nd.set_line_stranges_in_df()

,Unnamed: 0,TERM_i,TERM_f,Term,Energy,U2,U4,U6,Lambda,J_i,...,Boundaries_end_idx,Num_Gauss,Paired,Gauss_parameters,Bkg_parameters,Lambda_mean,Gauss_AUC,n,Line_strange,Coef
0,2,2P1/2,4I9/2,2P1/2-4I9/2,23223.0,0.0000,0.0396,0.0000,430.607587,0.5,...,50.0,3.0,False,"[[0.1024681673, 429.0542728957, 0.7518521063],...","(0.9169371886992258, 0.9008434837300567)",430.716,0.9053,1.55,0.090307,0.099754
1,3,2D3/2,4I9/2,2D3/2-4I9/2,21190.0,0.0000,0.0202,0.0001,471.920717,1.5,...,88.0,5.0,False,"[[0.0820270056, 461.2128484103, 3.4064912078],...","(0.9075022686531856, 0.8545756635578837)",469.786,3.7823,1.55,0.345920,0.091458
2,4,4G7/2,4I9/2,4G7/2-4I9/2,19058.0,0.0596,0.1709,0.0566,524.714031,3.5,...,153.0,5.0,True,"[[0.6467753975, 524.3829516513, 3.0680884216],...","(0.8602358053986678, 0.8357810753465884)",526.392,12.0222,1.55,0.981284,0.081623
3,5,4G7/2,4I9/2,4G7/2-4I9/2,17234.0,0.0707,0.1720,0.0274,580.248346,3.5,...,213.0,3.0,False,"[[2.3966986627, 572.4868144353, 3.0010358773],...","(0.8322025226732457, 0.7441538841378393)",580.087,82.6332,1.55,NaN,0.074067
4,6,4G5/2,4I9/2,4G5/2-4I9/2,17193.0,0.8975,0.4126,0.0346,581.632060,2.5,...,213.0,3.0,False,"[[2.9855617625, 581.6813038966, 4.3041608063],...","(0.8322070631063317, 0.7441577550009111)",581.470,82.6334,1.55,NaN,0.073891
5,7,4S3/2,4I9/2,4S3/2-4I9/2,13456.0,0.0000,0.0025,0.2347,743.162901,1.5,...,376.0,5.0,False,"[[1.3211423737, 735.5254123055, 2.9781305007],...","(0.6938051892418188, 0.6730769645085061)",743.001,40.5496,1.55,NaN,0.057827
6,8,4F7/2,4I9/2,4F7/2-4I9/2,13384.0,0.0011,0.0406,0.4272,747.160789,3.5,...,373.0,5.0,False,"[[0.9458383036, 735.1023791217, 2.36932294], [...","(0.6543955519529999, 0.6681193969638923)",746.999,41.7571,1.55,NaN,0.057517

### Подгонка параметров J-O

In [21]:
loss = 'rel'
fit_by = 'AUC'
jo_prist_Nd.fit_omegas(loss=loss, fit_by=fit_by)

         Current function value: 1.390206
         Iterations: 4
         Function evaluations: 400
         Gradient evaluations: 97

F:\Conda\envs\MatML\lib\site-packages\scipy\optimize\_minimize.py:733: OptimizeWarning: Desired error not necessarily achieved due to precision loss.
  res = _minimize_bfgs(fun, x0, args, jac, callback, **options)

{'Omega2': np.float64(4.0339243146),
 'Omega4': np.float64(3.3534207819),
 'Omega6': np.float64(3.357501125)}

In [26]:
jo_prist_Nd.omegas.values()

dict_values([np.float64(4.0339243146), np.float64(3.3534207819), np.float64(3.357501125)])

In [29]:
rounded_omega_Nd = np.round(np.array(list(jo_prist_Nd.omegas.values())),2).tolist()
rounded_omega_Nd

[4.03, 3.35, 3.36]

In [30]:
FileName_Nd = f'0.5_{path_to_Pristine_PZ_Nd.name.replace(".txt","_")}Omega_{rounded_omega_Nd}_{loss}_{fit_by}_400_800'
FileName_Nd

'0.5_Abs_Pristine_PZ_Nd_Omega_[4.03, 3.35, 3.36]_rel_AUC_400_800'

In [31]:
jo_prist_Nd.result_df.to_pickle(f'./{FileName_Nd}.pkl')

In [32]:
result_ND = jo_prist_Nd.result_df[['Term','U2','U4','U6','Lambda_mean','n','Gauss_AUC','Theor_AUC','Line_strange','Theor_line_strange','Grouped']]

In [33]:
result_ND

,Term,U2,U4,U6,Lambda_mean,n,Gauss_AUC,Theor_AUC,Line_strange,Theor_line_strange,Grouped
0,2P1/2-4I9/2,0.0000,0.0396,0.0000,430.716,1.55,0.9053,1.331234,0.090307,0.132795,False
1,2D3/2-4I9/2,0.0000,0.0202,0.0001,469.786,1.55,3.7823,0.744332,0.345920,0.068075,False
2,4G7/2-4I9/2,0.0596,0.1709,0.0566,526.392,1.55,12.0222,12.295069,0.981284,1.003556,False
3,4G7/2-4I9/2,0.0707,0.1720,0.0274,580.087,1.55,82.6332,12.879931,NaN,0.953982,True
4,4G5/2-4I9/2,0.8975,0.4126,0.0346,581.470,1.55,82.6334,69.294300,NaN,5.120238,True
5,4S3/2-4I9/2,0.0000,0.0025,0.2347,743.001,1.55,40.5496,13.771928,NaN,0.796389,True
6,4F7/2-4I9/2,0.0011,0.0406,0.4272,746.999,1.55,41.7571,27.381422,NaN,1.574911,True

In [34]:
result_ND.to_csv(f'./Nd_result_{FileName_Nd}.csv')