In [1]:
from pathlib import Path
import numpy as np
import pandas as pd

import import_ipynb
# import os
# cur_path = os.getcwd()
# os.chdir('path_to_Judd_Ofeld_Base')
from Judd_Ofeld_Base import RadiativeTransitionCalculator
# os.chdir(cur_path)

In [2]:
# Загрузка данных
df = pd.read_csv('./U_data/Nd_Carnal_Lower.txt')
df

,Unnamed: 0,TERM_i,TERM_f,Term,Energy,U2,U4,U6,Lambda,J_i,J_f,A_md_pre
0,0,2P1/2,4F3/2,2P1/2-4F3/2,11837.0,0.0131,0.0000,0.0000,844.808651,0.5,1.5,0.0
1,1,2P1/2,4S3/2,2P1/2-4S3/2,9767.0,0.0175,0.0000,0.0000,1023.855841,0.5,1.5,0.0
2,2,2P1/2,2D3/2,2P1/2-2D3/2,2033.0,0.0291,0.0000,0.0000,4918.839154,0.5,1.5,0.0
3,3,2P1/2,4F5/2,2P1/2-4F5/2,10798.0,0.0101,0.0000,0.0000,926.097425,0.5,2.5,0.0
4,4,2P1/2,4G5/2,2P1/2-4G5/2,6030.0,0.0346,0.0000,0.0000,1658.374793,0.5,2.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
107,107,2H11/2,4I15/2,2H11/2-4I15/2,9957.0,0.1293,0.0687,0.0000,1004.318570,5.5,7.5,0.0
108,108,4G11/2,4I13/2,4G11/2-4I13/2,17616.0,0.1283,0.3514,0.1609,567.665758,5.5,6.5,0.0
109,109,4G11/2,2K13/2,4G11/2-2K13/2,1929.0,0.0001,0.0077,0.0233,5184.033178,5.5,6.5,0.0
110,110,4G11/2,4I15/2,4G11/2-4I15/2,15566.0,0.5301,0.8915,0.1590,642.425800,5.5,7.5,0.0
111,111,2K13/2,4I15/2,2K13/2-4I15/2,13637.0,0.0000,0.0009,0.0064,733.299113,6.5,7.5,0.0

In [3]:
calculator = RadiativeTransitionCalculator(df, refractive_index=1.55)
omegas_pristine = [3.9, 3.03, 3.36]

In [4]:
calculator.df

,Unnamed: 0,TERM_i,TERM_f,Term,Energy,U2,U4,U6,Lambda,J_i,J_f,A_md_pre
0,0,2P1/2,4F3/2,2P1/2-4F3/2,11837.0,0.0131,0.0000,0.0000,844.808651,0.5,1.5,0.0
1,1,2P1/2,4S3/2,2P1/2-4S3/2,9767.0,0.0175,0.0000,0.0000,1023.855841,0.5,1.5,0.0
2,2,2P1/2,2D3/2,2P1/2-2D3/2,2033.0,0.0291,0.0000,0.0000,4918.839154,0.5,1.5,0.0
3,3,2P1/2,4F5/2,2P1/2-4F5/2,10798.0,0.0101,0.0000,0.0000,926.097425,0.5,2.5,0.0
4,4,2P1/2,4G5/2,2P1/2-4G5/2,6030.0,0.0346,0.0000,0.0000,1658.374793,0.5,2.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
107,107,2H11/2,4I15/2,2H11/2-4I15/2,9957.0,0.1293,0.0687,0.0000,1004.318570,5.5,7.5,0.0
108,108,4G11/2,4I13/2,4G11/2-4I13/2,17616.0,0.1283,0.3514,0.1609,567.665758,5.5,6.5,0.0
109,109,4G11/2,2K13/2,4G11/2-2K13/2,1929.0,0.0001,0.0077,0.0233,5184.033178,5.5,6.5,0.0
110,110,4G11/2,4I15/2,4G11/2-4I15/2,15566.0,0.5301,0.8915,0.1590,642.425800,5.5,7.5,0.0
111,111,2K13/2,4I15/2,2K13/2-4I15/2,13637.0,0.0000,0.0009,0.0064,733.299113,6.5,7.5,0.0

In [5]:
result = calculator.calculate(omegas_pristine, sample_name="Pristine_PZ_Nd")
result

,Term,Ajj,Bjj,Lifetime_ms,Lambda_nm,S_calc,Sample
0,2P1/2-4F3/2,102.248528,0.035705,0.349197,844.808651,0.051090,Pristine_PZ_Nd
1,2P1/2-4S3/2,76.733046,0.026795,0.349197,1023.855841,0.068250,Pristine_PZ_Nd
2,2P1/2-2D3/2,1.150710,0.000402,0.349197,4918.839154,0.113490,Pristine_PZ_Nd
3,2P1/2-4F5/2,59.842836,0.020897,0.349197,926.097425,0.039390,Pristine_PZ_Nd
4,2P1/2-4G5/2,35.701697,0.012467,0.349197,1658.374793,0.134940,Pristine_PZ_Nd
...,...,...,...,...,...,...,...
107,2H11/2-4I15/2,141.440342,0.839945,5.938514,1004.318570,0.712431,Pristine_PZ_Nd
108,4G11/2-4I13/2,2315.105550,0.365293,0.157787,567.665758,2.105736,Pristine_PZ_Nd
109,4G11/2-2K13/2,0.147258,0.000023,0.157787,5184.033178,0.102009,Pristine_PZ_Nd
110,4G11/2-4I15/2,4022.420206,0.634684,0.157787,642.425800,5.302875,Pristine_PZ_Nd
111,2K13/2-4I15/2,10.593172,1.000000,94.400428,733.299113,0.024231,Pristine_PZ_Nd

In [6]:
calculator.get_filtred_data(terms=['4F3/2-4I9/2', '4F3/2-4I11/2', '4F3/2-4I13/2'], result_df=result)

           Term         Ajj       Bjj  Lifetime_ms    Lambda_nm
0   4F3/2-4I9/2  781.846234  0.410078       0.5245   878.271562
1  4F3/2-4I11/2  934.773005  0.490288       0.5245  1051.856527
2  4F3/2-4I13/2  180.654139  0.094753       0.5245  1329.256945